name: DevelopBranchWorkflow

on:
  push:
    branches:
      - "develop"

jobs:
  CreateIssuesFromTodos:
    uses: KyeongminKang-GGQ/GithubAction-ContainerTest/.github/workflows/CreateIssueFromTodo.yml@main
    secrets: inherit
    with:
      repository: ${{ github.repository }}
      ref_name: ${{ github.ref_name }}

  DeployToDev:
    uses: KyeongminKang-GGQ/GithubAction-ContainerTest/.github/workflows/DeployToDev.yml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      repository: ${{ github.repository }}
      ref_name: ${{ github.ref_name }}
      commit: ${{ github.sha }}
      # DEV환경은 [ap-northeast-2] 로 고정
      environment: DEV
      region: ap-northeast-2
      account_id_dev: "118166980108"
      account_id_stg: "666644083535"
      account_id_prod: "071637104407"
      product_code: ggq
      application_code: lol_auth
      s3_api_doc_folder_name: ggq-lol-auth
