name: FeatureBranchWorkflow
on:
  workflow_dispatch:
  #push:
  # branches:
  #  - "feature/**"

jobs:
  GetAwsValue:
    uses: KyeongminKang-GGQ/GithubAction-ContainerTest/.github/workflows/GetAwsValue.yml@main
    with:
      # DEV환경은 [ap-northeast-2] 로 고정
      environment: DEV
      region: ap-northeast-2
      account_id_dev: "118166980108"
      account_id_stg: "666644083535"
      account_id_prod: "071637104407"
      product_code: ggq
      application_code: lol_auth
      s3_api_doc_folder_name: ggq-lol-auth

  Build:
    runs-on: ubuntu-latest
    needs: [GetAwsValue]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Test
        env:
          ECR_REGISTRY: ${{ needs.GetAwsValue.outputs.ecr_registry }}
          ECR_REPOSITORY: ${{ needs.GetAwsValue.outputs.ecr_repository }}
          IMAGE_TAG: ${{ github.sha }}
        #docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        run: |
          ls -al 
          echo ECR_REGISTRY = ${{ env.ECR_REGISTRY }}
          echo ECR_REPOSITORY = ${{ env.ECR_REPOSITORY }}
          echo IMAGE_TAG = ${{ env.IMAGE_TAG }}
