name: ManualDeployToDev

# feature 브랜치에서 DEV 환경에 배포 필요 시 수동으로 Workflow를 수행한다.
# 대상 feature 브랜치의 최신 commit으로 배포

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: 배포 환경 (수정 불가)
        options:
          - DEV
      region:
        type: choice
        required: true
        description: AWS region
        options:
          # DEV환경은 [ap-northeast-2] 로 고정
          - ap-northeast-2

jobs:
  DeployToDev:
    uses: KyeongminKang-GGQ/GithubAction-ContainerTest/.github/workflows/DeployToDev.yml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
    with:
      # Checkout 시 필요한 Input Data
      repository: ${{ github.repository }}
      ref_name: ${{ github.ref_name }}
      # AWS 배포 시 필요한 데이터
      commit: ${{ github.sha }}
      environment: ${{ inputs.environment }}
      region: ${{ inputs.region }}
      account_id_dev: "118166980108"
      account_id_stg: "666644083535"
      account_id_prod: "071637104407"
      product_name: ggq
      application_code: lol_auth
      s3_api_doc_folder_name: ggq-lol-auth
      # Slack 송신에 필요한 데이터
      server_name: Auth Server
