name: RollbackDeploy

# 태그이름으로 Rollback 배포 진행
# rc 버전 태그일 경우 STG 배포
# rc 버전 태그가 아닐 경우 PROD 배포

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: 배포할 tag 이름을 입력하세요.
      region:
        type: choice
        required: true
        description: 배포할 AWS region를 선택하세요.
        options:
          - ap-northeast-2

jobs:
  RollbackDeploy:
    uses: KyeongminKang-GGQ/GithubAction-ContainerTest/.github/workflows/RollbackDeploy.yml@main
    secrets: inherit
    with:
      # Checkout 시 필요한 Input Data
      repository: ${{ github.repository }}
      ref_name: ${{ github.ref_name }}
      # AWS 배포 시 필요한 데이터
      commit: ${{ github.sha }}
      environment: ${{ inputs.environment }}
      region: ${{ inputs.region }}
      account_id_dev: "118166980108"
      account_id_stg: "666644083535"
      account_id_prod: "071637104407"
      product_code: ggq
      application_code: lol_auth
      s3_api_doc_folder_name: ggq-lol-auth
      # Slack 송신에 필요한 데이터
      server_name: Auth Server
