name: SetTagForProd

# release/hotfix 브랜치에서 main으로 머지 후 PROD 환경 배포 전 Tag를 생성하기 위한 수동 Workflow
# hotfix 브랜치면 1.0.0+hotfix.yymmdd
# release 브랜치면 1.0.0+yymmdd
# main에 Tag 생성 후 main에 생성된 Tag로 서버 배포를 진행한다.

on:
  workflow_dispatch:

jobs:
  SetTagForProd:
    uses: KyeongminKang-GGQ/GithubAction-ContainerTest/.github/workflows/SetTagForProd.yml@main
    with:
      repository: ${{ github.repository }}
      ref_name: ${{ github.ref_name }}
