name: SetVariables

on:
  workflow_call:
    outputs:
      account_id_dev:
        value: ${{ jobs.SetVariables.outputs.account_id_dev }}
      account_id_stg:
        value: ${{ jobs.SetVariables.outputs.account_id_stg }}
      account_id_prod:
        value: ${{ jobs.SetVariables.outputs.account_id_prod }}
      product_code:
        value: ${{ jobs.SetVariables.outputs.product_code }}
      application_code:
        value: ${{ jobs.SetVariables.outputs.application_code }}
      s3_api_doc_folder_name:
        value: ${{ jobs.SetVariables.outputs.s3_api_doc_folder_name }}
      server_name:
        value: ${{ jobs.SetVariables.outputs.server_name }}

jobs:
  SetVariables:
    runs-on: ubuntu-latest
    outputs:
      account_id_dev: ${{ env.json_account_id_dev }}
      account_id_stg: ${{ env.json_account_id_stg }}
      account_id_prod: ${{ env.json_account_id_prod }}
      product_code: ${{ env.json_product_code }}
      application_code: ${{ env.json_application_code }}
      s3_api_doc_folder_name: ${{ env.json_s3_api_doc_folder_name }}
      server_name: ${{ env.json_server_name }}
    steps:
      - uses: actions/checkout@v2
      - name: JSON to variables
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: ".github/workflows/variables.json"
