name: GetUnitTestStatus

on:
  workflow_dispatch:
  #schedule:
  # - cron: "0 0 * * *"

jobs:
  NotifyUnitTest:
    permissions:
      contents: write
      checks: write
      pull-requests: write
      repository-projects: write
    runs-on: self-hosted
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - uses: actions/checkout@v3
        with:
          repository: ggqcompany/back-node-master-application-server
          ref: develop
          path: application
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: LoveToKnow/slackify-markdown-action@v1
        id: slackify
        with:
          text: ${{ steps.coverage_application.outputs.report }}
      - run: |
          echo SLACKIFY = ${{ steps.slackify.outputs.text }}
